Repository gdscjgec/Image-Editor, pull requests merged in 2022-02, with the labels that each got.

#61 Changed By Shreyan
  css/style.css
  index.html
Labels: JWOC, Easy: 1 day, easy

#63 UI Enhancement
  css/style.css
  images/pink.jpg
  index.html
Labels: JWOC, Easy: 1 day, easy

#71 implementation of other useful Filter as of #9
  css/style.css
  index.html
  js/app.js
Labels: JWOC, Easy: 1 day, easy

#73 issue #72 UI design added
  assets/ui/Image Editor UI Design.fig
Labels: JWOC, Easy: 1 day, easy

#81 Crop enhancements and better ux
  css/style.css
  js/app.js
Labels: JWOC, Easy: 1 day, easy

#82 Enhanced the overall Styling.
  css/style.css
  index.html
Labels: JWOC, Easy: 1 day, easy

#84 Redesigned the page
  assets/svg/download.svg
  css/range-input.css
  css/style.css
  css/styleOld.css
  index.html
  pages/index.html
Labels: JWOC, Hard: 4 days, hard

#87 Add blur slider
  index.html
  js/app.js
Labels: JWOC, Medium: 2-3 days, medium

#88 Update README.md
  README.md
Labels: JWOC, easy

#92 Made the webpage responsive
  css/style.css
Labels: JWOC, Easy: 1 day, easy

#94 Implement different filters
  css/style.css
  index.html
  js/app.js
Labels: JWOC, Easy: 1 day, easy
